//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkOtomasyonu.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_islemler
    {
        public int id { get; set; }
        public Nullable<int> musteriId { get; set; }
        public int aracId { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public bool Durum { get; set; }
        public int otoparkId { get; set; }
    
        public virtual tbl_parkAlani tbl_parkAlani { get; set; }
        public virtual tbl_arac tbl_arac { get; set; }
        public virtual tbl_musteri tbl_musteri { get; set; }
    }
}
